### ISSUE TITLE
Stored XSS

### ISSUE THREAD

**Issue by simonuvarov** [uisky/notabenoid#11]
При создании новой главы в переводе отсуствует фильтрация управляющих символов HTML, в связи с чем возможно осуществить атаку на пользователя.

Пример можно посмотреть вот тут:
http://notabenoid.org/book/66011

Либо под общим аккаунтом:
https://opennota.duckdns.org/book/66011

В качестве названия главы в переводе указана строка:

```
<svg/onload=alert(/xss/)>
```

**Comment by opennota** [comment]
Confirmed.

**Comment by opennota** [comment]
В [notabenoid/notabenoid](https://github.com/notabenoid/notabenoid) пофикшено, ждём @uisky.
